import { z } from "zod";
import { tool } from "ai";

// Schema for the suggest_destinations tool
const suggestDestinationsSchema = z.object({
  vibe: z.string().describe("The vibe user wants, e.g., 'adventure', 'luxury', 'culture', 'relax'"),
  suggested_cities: z
    .array(z.string())
    .describe("List of 3 cities matching the vibe generated by the AI"),
});

// Helper to fetch real image from Unsplash
async function getUnsplashImage(query: string, accessKey?: string): Promise<string> {
  if (!accessKey) {
    // Return placeholder if no API key configured
    return `https://source.unsplash.com/800x600/?${encodeURIComponent(query)},travel`;
  }

  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=1&client_id=${accessKey}`;

  try {
    const res = await fetch(url);
    const data = (await res.json()) as { results?: { urls?: { regular?: string } }[] };
    return data.results?.[0]?.urls?.regular || `https://source.unsplash.com/800x600/?${encodeURIComponent(query)},travel`;
  } catch {
    return `https://source.unsplash.com/800x600/?${encodeURIComponent(query)},travel`;
  }
}

// Helper to fetch real description from Wikipedia
async function getWikiSummary(city: string): Promise<string> {
  const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(city)}`;
  try {
    const res = await fetch(url);
    const data = (await res.json()) as { extract?: string };
    return data.extract || "A beautiful destination waiting to be explored.";
  } catch {
    return "A beautiful destination waiting to be explored.";
  }
}

// Factory function to create the tool with optional env access
export function createSuggestDestinationsTool(unsplashAccessKey?: string) {
  return tool({
    description:
      "Get real photos and details for destinations matching a travel vibe. The AI should suggest 3 cities that match the user's desired vibe, then this tool fetches real images and descriptions for them.",
    inputSchema: suggestDestinationsSchema,
    execute: async (input) => {
      const { vibe, suggested_cities } = input as {
        vibe: string;
        suggested_cities: string[];
      };

      // Fetch real data for each suggested city in parallel
      const detailedDestinations = await Promise.all(
        suggested_cities.map(async (city) => {
          const [imageUrl, description] = await Promise.all([
            getUnsplashImage(city, unsplashAccessKey),
            getWikiSummary(city),
          ]);

          return {
            city,
            vibe,
            description,
            imageUrl,
          };
        })
      );

      return {
        vibe,
        destinations: detailedDestinations,
        message: `Found ${detailedDestinations.length} destination(s) matching "${vibe}" vibe.`,
      };
    },
  });
}

// Default export for simple usage (without Unsplash API)
export const suggestDestinations = createSuggestDestinationsTool();